# Generated by Django 5.0.3 on 2024-04-16 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('alt_title', models.CharField(max_length=255)),
                ('developers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_store_app.developer')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_store_app.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_store_app.platform')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_store_app.tag')),
            ],
        ),
    ]
