# Generated by Django 5.0.3 on 2024-05-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0002_game_release_date_alter_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
