# Generated by Django 5.0.3 on 2024-05-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0003_game_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
