# Generated by Django 5.0.3 on 2024-05-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0008_game_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
