# Generated by Django 5.0.3 on 2024-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0009_alter_developer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game_store_app.genre'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(to='game_store_app.developer'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='game_store_app.tag'),
        ),
    ]
