# Generated by Django 5.0.3 on 2024-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0010_remove_game_genre_game_genres_remove_game_developers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='game_store_app.platform'),
        ),
    ]
