# Generated by Django 5.0.3 on 2024-05-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0011_remove_game_platform_game_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developers',
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_store_app.developer'),
            preserve_default=False,
        ),
    ]
