# Generated by Django 5.0.3 on 2024-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0013_rename_developers_game_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.CharField(default='https://www.youtube.com/watch?v=XKeAJDtEe9E', max_length=255),
            preserve_default=False,
        ),
    ]
