# Generated by Django 5.0.3 on 2024-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0014_game_trailer_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='trailer_url',
            new_name='video_id',
        ),
    ]
