# Generated by Django 5.0.3 on 2024-05-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0016_blogpost_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game_store_app.game'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
