# Generated by Django 5.0.3 on 2024-05-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0019_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
